### PR TITLE
update MVD board to include COMM LED

### PR DESCRIPTION
**Pull request by jamesadevine**

### CODE REVIEW

**Comment by jamesadevine** [comment]
@mmoskal I'm not sure how the mapping is done here. PB14 has hex value 0x2e, but I copied the PB14 value from the generic stm32f4 board.

**Comment by jamesadevine** [comment]
Actually, think I was looking at the wrong define...

**Comment by mmoskal** [comment]
Best to use https://microsoft.github.io/uf2/patcher/ - drop the .h file and add your changes

**Comment by mmoskal** [comment]
Did it independently

**Pull request closed without merging**
